import { WeaponConfig, WeaponType } from '../types';

export const WEAPON_CONFIGS: Record<WeaponType, WeaponConfig> = {
  pistol: {
    id: 'pistol',
    name: 'Tactical Pistol',
    nameAr: 'مسدس تكتيكي',
    damage: 15,
    fireRate: 4.8, // 4.8 shots per sec
    magazineSize: 12,
    reloadTime: 1.1,
    spread: 0.03,
    bulletSpeed: 1300,
    bulletCount: 1,
    bulletLife: 2.0,
    recoil: 4,
    range: 1800,
    isAutomatic: false,
    color: '#fbbf24', // golden yellow bullet
    barrelLength: 26,
    iconName: 'Crosshair',
  },
  rifle: {
    id: 'rifle',
    name: 'Assault Rifle M4',
    nameAr: 'بندقية هجومية M4',
    damage: 13,
    fireRate: 8.5,
    magazineSize: 30,
    reloadTime: 1.6,
    spread: 0.05,
    bulletSpeed: 1650,
    bulletCount: 1,
    bulletLife: 2.5,
    recoil: 5,
    range: 2600,
    isAutomatic: true,
    color: '#f97316', // orange tracer
    barrelLength: 38,
    iconName: 'Zap',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Combat Shotgun',
    nameAr: 'شوزن قتالي',
    damage: 12, // 12 x 6 = 72 max burst
    fireRate: 1.6,
    magazineSize: 6,
    reloadTime: 2.0,
    spread: 0.18,
    bulletSpeed: 1250,
    bulletCount: 6,
    bulletLife: 1.2,
    recoil: 15,
    range: 1200,
    isAutomatic: false,
    color: '#ef4444', // red pellets
    barrelLength: 32,
    iconName: 'ShieldAlert',
  },
  rocket: {
    id: 'rocket',
    name: 'Rocket Launcher RPG',
    nameAr: 'قاذف صواريخ RPG',
    damage: 75,
    fireRate: 1.0,
    magazineSize: 3,
    reloadTime: 2.4,
    spread: 0.015,
    bulletSpeed: 950,
    bulletCount: 1,
    bulletLife: 4.2,
    recoil: 22,
    range: 3200,
    isAutomatic: false,
    color: '#eab308',
    barrelLength: 42,
    splashRadius: 160,
    splashDamage: 85,
    iconName: 'Flame',
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper Rifle AWM',
    nameAr: 'قناصة AWM',
    damage: 70,
    fireRate: 0.9,
    magazineSize: 5,
    reloadTime: 2.2,
    spread: 0.005,
    bulletSpeed: 2400,
    bulletCount: 1,
    bulletLife: 3.2,
    recoil: 18,
    range: 4000,
    isAutomatic: false,
    color: '#38bdf8', // bright cyan tracer
    barrelLength: 48,
    iconName: 'Target',
  },
};

export const GRENADE_CONFIG = {
  throwSpeed: 650,
  gravity: 700,
  bounciness: 0.55,
  friction: 0.96,
  fuseTime: 2.2, // seconds
  damage: 85,
  splashRadius: 160,
  maxGrenades: 3,
};
